#!/usr/bin/python3
import json

result = []

with open('tao.txt') as f:
    gathered = []

    for line in f:
        try:
            number = int(line)
        except ValueError:
            number = None

        if number is not None:
            if len(gathered) > 0:
                result.append(gathered)
                gathered = []
        else:
            gathered.append(line.strip())

with open('tao.6.js', 'w') as f:
    f.write('export default ')
    json.dump(result, f)
    f.write(';')

